# Generated by Django 4.1.6 on 2023-03-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_remove_book_author_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='status',
            field=models.CharField(choices=[('Active', 'Активный'), ('Inactive', 'Не активный')], default='Inactive', max_length=8, verbose_name='Статус читателя'),
        ),
    ]
