# Generated by Django 4.1.6 on 2023-03-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_book_quantity_of_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quantity_of_books',
            field=models.PositiveIntegerField(default=0, verbose_name='Колличество книг'),
        ),
    ]
